# Generated by Django 4.2.1 on 2023-05-21 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Executive Suite', 'Executive Suite'), ('Super Deluxe', 'Super Deluxe')], max_length=120, null=True)),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Airport Pick-up', 'pick_up'), ('Airport Drop-off', 'drop_off'), ('Food & Restaurant', 'food'), ('Spa & Fitness', 'spa'), ('Sports & Gaming', 'sports'), ('Event & Party', 'party'), ('GYM & Yoga', 'gym')], max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date_time', models.DateTimeField()),
                ('extra_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grand_oasis.extraservice')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('duration', models.CharField(max_length=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grand_oasis.roommodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='extraservice',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='grand_oasis.reservationmodel'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grand_oasis.servicetype'),
        ),
        migrations.CreateModel(
            name='ContactModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('msg_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to=settings.AUTH_USER_MODEL)),
                ('msg_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
