# Generated by Django 4.2.1 on 2023-05-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Executive Suite', 'Executive Suite'), ('Super Deluxe', 'Super Deluxe')], max_length=120, null=True)),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('price_per_night', models.IntegerField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grand_oasis.roommodel')),
            ],
        ),
    ]
