# Generated by Django 4.2.1 on 2023-05-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0002_alter_roommodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
