# Generated by Django 4.2.1 on 2023-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0004_roommodel_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
