# Generated by Django 4.2.1 on 2023-05-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0006_clientloginmodel_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
