# Generated by Django 4.2.1 on 2023-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0007_alter_reservationmodel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='checkout',
            field=models.DateField(),
        ),
    ]
