# Generated by Django 4.2.1 on 2023-05-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0008_alter_reservationmodel_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='room',
        ),
    ]
