# Generated by Django 4.2.1 on 2023-05-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0009_remove_reservationmodel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grand_oasis.roommodel'),
        ),
    ]
