# Generated by Django 4.2.1 on 2023-05-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0010_reservationmodel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grand_oasis.roommodel'),
        ),
    ]
