# Generated by Django 4.2.1 on 2023-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_oasis', '0011_alter_reservationmodel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
